[package]
name = "dexterws-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm18-0"] }
